name: docker container check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build container
        run: docker-compose build
        working-directory: ${{env.working-directory}}

      - name: run container
        run: docker-compose up -d
        working-directory: ${{env.working-directory}}

      - name: check container
        run: |
          sleep 10
          docker ps

      - name: check net
        run: |
          netstat -a -n -o
          nc -vz 127.0.0.1 7034

      - name: check container connection
        run: curl http://127.0.0.1:7034
